#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), *%w(.. lib)))

require "optparse"
require "caravan"

options = {}
option_parser = OptionParser.new do |opts|
  opts.banner = "Caravan #{Caravan::VERSION}. Copyright (c) David Zhang. 2017\n"
  opts.separator ""

  opts.on("-s SOURCE_PATH", "--source SOURCE_PATH", "Source path") do |value|
    options[:src] = value
  end

  opts.on("-d DEST_PATH", "--dest DEST_PATH", "Destination path") do |value|
    options[:dst] = value
  end

  opts.on("-m DEPLOY_MODE", "--mode DEPLOY_MODE", "Deploy mode") do |value|
    options[:mode] = value || "shell"
  end

  opts.on("-i IGNORE_FILES", "--ignore IGNORE_FILES", "ignore files") do |value|
    options[:ignore] = value || "\.(git|svn)$"
  end

  opts.on_tail("--version", "Show version") do
    puts Caravan::VERSION
    exit
  end
end.parse!(ARGV)

if options.key?(:src) && options.key?(:dst)
    Caravan.start(options)
end
